name: fitness_dashboard_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  animate_do: ^3.3.4
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  socket_io_client: ^2.0.3+1
  auto_route: ^9.2.2
  window_manager: ^0.4.2
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.1
  path_provider: ^2.1.5
  excel: ^4.0.6
  open_file: ^3.5.10
  pdf: ^3.11.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  printing: ^5.13.4
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/playstore.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/playstore.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/playstore.png"